### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jmas** [jmas/charttty#1]
- [ ] Events
  - [x] URL
  - [x] E-mail
  - [ ] SMS
  - [ ] Chrome Notifications (need to develop Chrome Extension)
  - [ ] Push Notifications (need to develop Cordova App)
- [ ] Password Recovery
- [ ] **Data filters**
  - [ ] **Filter by date range for Data section**
  - [ ] **Filter by date range for each chart**
- [ ] Custom charts
  - [ ] [Pie](http://www.highcharts.com/demo/pie-basic)
  - [ ] [Gauge Solid](http://www.highcharts.com/demo/gauge-solid)
  - [ ] [Spy Web](http://www.highcharts.com/demo/polar-spider)
- [ ] Database backup
- [ ] Export to CSV
- [ ] API
  - [x] Insert data
  - [x] Get data
  - [ ] Get charts list
  - [ ] Create/Edit/Delete charts
  - [ ] Edit profile
- [ ] Documentation update
  - [x] API methods
  - [ ] Arduino and ESP examples
  - [ ] Video
- [ ] Chrome Extension
- [ ] Cordova App
  - [ ] Android
  - [ ] iOS
